SELECT
    CONCAT(QUARTER, 'Q') AS QUARTER
    , COUNT(ID) AS ECOLI_COUNT
FROM
    (
        SELECT 
            ID
            , CEILING(MONTH(DIFFERENTIATION_DATE) / 3) AS QUARTER
        FROM
            ECOLI_DATA
     ) Q
GROUP BY
    QUARTER
ORDER BY
    QUARTER ASC